swagger: "2.0"
info:
  version: "0.0.1"
  title: Quests-Reality
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /api/v1
# 
schemes:
  # tip: remove http to make production-grade
  - http
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /main:
    # binds a127 app logic to a route
    x-swagger-router-controller: main
    get:
      description: Returns parametres of Quests
      # used as the method name of the controller
      operationId: main
      parameters:
        - name: parametres
          in: query
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/QuestsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /genres:
    x-swagger-router-controller: genres
    get:
      description: Returns parametres of Quests
      # used as the method name of the controller
      operationId: genres
      parameters:
        - name: parametres
          in: query
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/GenresResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /comments:
    x-swagger-router-controller: comments
    get:
      description: Returns list of comments
      # used as the method name of the controller
      operationId: comments
      parameters:
        - name: parametres
          in: query
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/CommentsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /map:
    x-swagger-router-controller: map
    get:
      description: Returns map paremetres
      # used as the method name of the controller
      operationId: map
      parameters:
        - name: parametres
          in: query
          required: false
          type: string
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/MapResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  MapResponse:
    type: array
    items:
      $ref: "#/definitions/Map"
  Map:
    required:
      - id
    properties:
      id:
        type: string
      name:
        type: string
      genre:
        type: string
      coorX:
        type: integer
      coorY:
        type: integer
  
  CommentsResponse:
    type: array
    items:
      $ref: "#/definitions/Comments"
  
  Comments:
    required:
      - id
    properties:
      id:
        type: string
      name: 
        type: string
      comment:
        type: string
      date:
        type: string
      image:
        type: string

  GenresResponse:
    type: array
    items:
      $ref: "#/definitions/Genres"

  Genres:
    required:
      - id
    properties:
      genre:
        type: string
      name:
        type: string
      image:
        type: string
      id:
        type: string
      description:
        type: string

  QuestsResponse:
    type: array
    items:
      $ref: "#/definitions/Quests"
      
  Quests:
    required: 
      - id
    properties:
      id:
        type: string
      name:
        type: string
      genre:
        type: string
      image:
        type: string
      description:
        type: string
        
  ErrorResponse:
    properties:
      message:
        type: string
    
